version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - 27017:27017

  nodejs:
    build:
      context: ./webs
      dockerfile: Dockerfile
    ports:
      - 8000:8000
