# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
# RUN npm ci
RUN npm install

# Copy the application files to the container
COPY . .

# Expose the port on which the application will run
EXPOSE 8000

# Define the command to start the application
CMD ["node", "index.js"]